### ISSUE TITLE
ssl.SSLError: [SSL] PEM lib

### ISSUE THREAD

**Issue by pawp81** [secureworks/squarephish#1]
Do you have any suggestion what could be causing this error:
```
2022-12-22 12:57:51,353] [info]         squish.py:238  - Starting: SquarePhish -- v0.1.0
 * Serving Flask app "squarephish.modules.server" (lazy loading)
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: off
Traceback (most recent call last):
  File "/opt/squarephish/./squish.py", line 262, in <module>
    app.run(
  File "/usr/lib/python3/dist-packages/flask/app.py", line 990, in run
    run_simple(host, port, self, **options)
  File "/usr/lib/python3/dist-packages/werkzeug/serving.py", line 1052, in run_simple
    inner()
  File "/usr/lib/python3/dist-packages/werkzeug/serving.py", line 996, in inner
    srv = make_server(
  File "/usr/lib/python3/dist-packages/werkzeug/serving.py", line 847, in make_server
    return ThreadedWSGIServer(
  File "/usr/lib/python3/dist-packages/werkzeug/serving.py", line 766, in __init__
    self.socket = ssl_context.wrap_socket(sock, server_side=True)
  File "/usr/lib/python3/dist-packages/werkzeug/serving.py", line 656, in wrap_socket
    return ssl.wrap_socket(
  File "/usr/lib/python3.9/ssl.py", line 1402, in wrap_socket
    context.load_cert_chain(certfile, keyfile)
ssl.SSLError: [SSL] PEM lib (_ssl.c:4044)
```
My settings.config file has certificate and private key files configured:
CERT_CRT             = "cert.crt"                                                               # Server SSL certificate .crt file
CERT_KEY             = "dcf_private.key"                                                        # Server SSL certificate .key file

I had obtained .pem file from Let's Encrypt which I then converted to private key and certificate files using:
```
openssl pkey -in /etc/letsencrypt/live/dcf.ppartyka.pl/privkey.pem -out cert.crt
openssl x509 -outform der -in /etc/letsencrypt/live/my_domain/fullchain.pem -out cert.crt
```

**Comment by nromsdahl-scwx** [comment]
I've never ran into this issue, but would try the following:
- Ensure the user squarephish is running as has access to the directory the keys are stored in.
- Try adding the full path to the configuration file.
- View the cert files to make sure they are correct private and certificate files.
This link and answer will have more info on the certs.  https://stackoverflow.com/questions/50389883/generate-crt-key-ssl-files-from-lets-encrypt-from-scratch

**Comment by nromsdahl-scwx** [comment]
Closing due to no response.  Assume you got it worked out.
