### ISSUE TITLE
Rephresh.py error

### ISSUE THREAD

**Issue by hacker213** [secureworks/squarephish#4]
When attempting to utilize the acquired token I am getting the following error. I have verified that time on the server by the timestamp on the emails in O365, as well and synching the NTP on the Parrot host. 

I have obfuscated some of the specific information but all fields returned to the point of the RuntimeError: 0

[2023-01-06 14:03:45,529] [debug]       rephresh.py:119  - Modules:    ['all']
[2023-01-06 14:03:45,529] [debug]       rephresh.py:124  - Token file: len.noe@xxxxxxxlab.com.tokeninfo.json
[2023-01-06 14:03:45,529] [debug]       rephresh.py:137  - Token UPN:  user.one@xxxxxxxlab.com
[2023-01-06 14:03:45,529] [debug]       rephresh.py:138  - Domain:     xxxxxxxlab.com
[2023-01-06 14:03:45,532] [debug] connectionpool.py:973  - Starting new HTTPS connection (1): login.windows.net:443
[2023-01-06 14:03:48,449] [debug] connectionpool.py:452  - https://login.windows.net:443 "GET /XXXXX.com/.well-known/openid-configuration HTTP/1.1" 200 1736
[2023-01-06 14:03:48,451] [debug]       rephresh.py:146  - Tenant ID:  XXXXX-00f3-4c70-8454-2a33bdbxxxx
[2023-01-06 14:03:48,451] [info]       rephresh.py:156  - Output directory: output/user.one@xxxxxxxlab.com.20230106200348
[2023-01-06 14:03:48,451] [info]         emails.py:67   - Acquiring refresh token for 'Microsoft Office'
[2023-01-06 14:03:48,451] [debug]          retry.py:333  - Converted retries value: 1 -> Retry(total=1, connect=None, read=None, redirect=None, status=None)
[2023-01-06 14:03:48,453] [debug] connectionpool.py:973  - Starting new HTTPS connection (1): login.microsoftonline.com:443
[2023-01-06 14:03:49,362] [debug] connectionpool.py:452  - https://login.microsoftonline.com:443 "GET /XXXXX-00f3-4c20-8454-2a33bdXXXXX/v2.0/.well-known/openid-configuration HTTP/1.1" 200 1753
[2023-01-06 14:03:49,363] [debug]      authority.py:130  - openid_config = {'token_endpoint': 'https://login.microsoftonline.com/XXXXX-00f3-4c70-8454-2a33bdbxxxx/oauth2/v2.0/token', 'token_endpoint_auth_methods_supported': ['client_secret_post', 'private_key_jwt', 'client_secret_basic'], 'jwks_uri': 'https://login.microsoftonline.com/XXXXX-00f3-4c70-8454-2a33bdbxxxx/discovery/v2.0/keys', 'response_modes_supported': ['query', 'fragment', 'form_post'], 'subject_types_supported': ['pairwise'], 'id_token_signing_alg_values_supported': ['RS256'], 'response_types_supported': ['code', 'id_token', 'code id_token', 'id_token token'], 'scopes_supported': ['openid', 'profile', 'email', 'offline_access'], 'issuer': 'https://login.microsoftonline.com/XXXXX-00f3-4c70-8454-2a33bdbxxxx/v2.0', 'request_uri_parameter_supported': False, 'userinfo_endpoint': 'https://graph.microsoft.com/oidc/userinfo', 'authorization_endpoint': 'https://login.microsoftonline.com/XXXXX-00f3-4c70-8454-2a33bdbxxxx/oauth2/v2.0/authorize', 'device_authorization_endpoint': 'https://login.microsoftonline.com/XXXXX-00f3-4c70-8454-2a33bdbxxxx/oauth2/v2.0/devicecode', 'http_logout_supported': True, 'frontchannel_logout_supported': True, 'end_session_endpoint': 'https://login.microsoftonline.com/XXXXX-00f3-4c70-8454-2a33bdbxxxx/oauth2/v2.0/logout', 'claims_supported': ['sub', 'iss', 'cloud_instance_name', 'cloud_instance_host_name', 'cloud_graph_host_name', 'msgraph_host', 'aud', 'exp', 'iat', 'auth_time', 'acr', 'nonce', 'preferred_username', 'name', 'tid', 'ver', 'at_hash', 'c_hash', 'email'], 'kerberos_endpoint': 'https://login.microsoftonline.com/XXXXX-00f3-4c70-8454-2a33bdbxxxx/kerberos', 'tenant_region_scope': 'EU', 'cloud_instance_name': 'microsoftonline.com', 'cloud_graph_host_name': 'graph.windows.net', 'msgraph_host': 'graph.microsoft.com', 'rbac_url': 'https://pas.windows.net'}
[2023-01-06 14:03:49,363] [debug]    application.py:567  - Broker enabled? False
[2023-01-06 14:03:49,364] [debug]      telemetry.py:37   - Generate or reuse correlation_id: 1376338d-1ccb-4ef9-a877-2f14335590c9
[2023-01-06 14:03:49,660] [debug] connectionpool.py:452  - https://login.microsoftonline.com:443 "POST /XXXXX-00f3-4c70-8454-2a33bdbxxxx/oauth2/v2.0/token HTTP/1.1" 200 7326
[2023-01-06 14:03:49,661] [debug]    token_cache.py:123  - event={
    "client_id": "XXXXX-37b5-1407-XXXXX-292ab01caad2",
    "data": {
        "refresh_token": "********",
        "scope": [
            "offline_access",
            "profile",
            "openid",
            ".default"
        ]
    },
    "environment": "login.microsoftonline.com",
    "grant_type": "refresh_token",
    "params": null,
    "response": {
        "access_token": "********",
        "client_info": "eyJ1aWQiOiI0MZjXXXXXNTEiLCJ1dGlkIjoiMzgwNmEwNzBiN2M2OXXXXXMy00YzIwLTgGJhZGQ1M0NTQtMmEzM2JkYjE2Y2YzIn0",
        "expires_in": 7913,
        "ext_expires_in": 7913,
        "foci": "1",
        "id_token": "********",
        "refresh_in": 3956,
        "refresh_token": "********",
        "scope": "email openid profile 00000003-0000-0000-c000-000000000000/AuditLog.Read.All 00000003-0000-0000-c000-000000000000/Calendar.ReadWrite 00000003-0000-0000-c000-000000000000/Calendars.Read.Shared 00000003-0000-0000-c000-000000000000/Calendars.ReadWrite 00000003-0000-0000-c000-000000000000/Contacts.ReadWrite 00000003-0000-0000-c000-000000000000/DataLossPreventionPolicy.Evaluate 00000003-0000-0000-c000-000000000000/DeviceManagementConfiguration.Read.All 00000003-0000-0000-c000-000000000000/DeviceManagementConfiguration.ReadWrite.All 00000003-0000-0000-c000-000000000000/Directory.AccessAsUser.All 00000003-0000-0000-c000-000000000000/Directory.Read.All 00000003-0000-0000-c000-000000000000/Files.Read 00000003-0000-0000-c000-000000000000/Files.Read.All 00000003-0000-0000-c000-000000000000/Files.ReadWrite.All 00000003-0000-0000-c000-000000000000/Group.Read.All 00000003-0000-0000-c000-000000000000/Group.ReadWrite.All 00000003-0000-0000-c000-000000000000/InformationProtectionPolicy.Read 00000003-0000-0000-c000-000000000000/Mail.ReadWrite 00000003-0000-0000-c000-000000000000/Notes.Create 00000003-0000-0000-c000-000000000000/People.Read 00000003-0000-0000-c000-000000000000/People.Read.All 00000003-0000-0000-c000-000000000000/Printer.Read.All 00000003-0000-0000-c000-000000000000/PrintJob.ReadWriteBasic 00000003-0000-0000-c000-000000000000/SensitiveInfoType.Detect 00000003-0000-0000-c000-000000000000/SensitiveInfoType.Read.All 00000003-0000-0000-c000-000000000000/SensitivityLabel.Evaluate 00000003-0000-0000-c000-000000000000/Tasks.ReadWrite 00000003-0000-0000-c000-000000000000/TeamMember.ReadWrite.All 00000003-0000-0000-c000-000000000000/TeamsTab.ReadWriteForChat 00000003-0000-0000-c000-000000000000/User.Read.All 00000003-0000-0000-c000-000000000000/User.ReadBasic.All 00000003-0000-0000-c000-000000000000/User.ReadWrite 00000003-0000-0000-c000-000000000000/Users.Read 00000003-0000-0000-c000-000000000000/.default",
        "token_type": "Bearer"
    },
    "scope": [
        "email",
        "openid",
        "profile",
        "00000003-0000-0000-c000-000000000000/AuditLog.Read.All",
        "00000003-0000-0000-c000-000000000000/Calendar.ReadWrite",
        "00000003-0000-0000-c000-000000000000/Calendars.Read.Shared",
        "00000003-0000-0000-c000-000000000000/Calendars.ReadWrite",
        "00000003-0000-0000-c000-000000000000/Contacts.ReadWrite",
        "00000003-0000-0000-c000-000000000000/DataLossPreventionPolicy.Evaluate",
        "00000003-0000-0000-c000-000000000000/DeviceManagementConfiguration.Read.All",
        "00000003-0000-0000-c000-000000000000/DeviceManagementConfiguration.ReadWrite.All",
        "00000003-0000-0000-c000-000000000000/Directory.AccessAsUser.All",
        "00000003-0000-0000-c000-000000000000/Directory.Read.All",
        "00000003-0000-0000-c000-000000000000/Files.Read",
        "00000003-0000-0000-c000-000000000000/Files.Read.All",
        "00000003-0000-0000-c000-000000000000/Files.ReadWrite.All",
        "00000003-0000-0000-c000-000000000000/Group.Read.All",
        "00000003-0000-0000-c000-000000000000/Group.ReadWrite.All",
        "00000003-0000-0000-c000-000000000000/InformationProtectionPolicy.Read",
        "00000003-0000-0000-c000-000000000000/Mail.ReadWrite",
        "00000003-0000-0000-c000-000000000000/Notes.Create",
        "00000003-0000-0000-c000-000000000000/People.Read",
        "00000003-0000-0000-c000-000000000000/People.Read.All",
        "00000003-0000-0000-c000-000000000000/Printer.Read.All",
        "00000003-0000-0000-c000-000000000000/PrintJob.ReadWriteBasic",
        "00000003-0000-0000-c000-000000000000/SensitiveInfoType.Detect",
        "00000003-0000-0000-c000-000000000000/SensitiveInfoType.Read.All",
        "00000003-0000-0000-c000-000000000000/SensitivityLabel.Evaluate",
        "00000003-0000-0000-c000-000000000000/Tasks.ReadWrite",
        "00000003-0000-0000-c000-000000000000/TeamMember.ReadWrite.All",
        "00000003-0000-0000-c000-000000000000/TeamsTab.ReadWriteForChat",
        "00000003-0000-0000-c000-000000000000/User.Read.All",
        "00000003-0000-0000-c000-000000000000/User.ReadBasic.All",
        "00000003-0000-0000-c000-000000000000/User.ReadWrite",
        "00000003-0000-0000-c000-000000000000/Users.Read",
        "00000003-0000-0000-c000-000000000000/.default"
    ],
    "token_endpoint": "https://login.microsoftonline.com/XXXXX-00f3-4c70-8454-2a33bdbxxxx/oauth2/v2.0/token"
}
Traceback (most recent call last):
  File "/home/u213/git/squarephish/rephresh/rephresh.py", line 171, in <module>
    Emails.fetch(module_state=module_state, scopes=scopes)
  File "/home/u213/git/squarephish/rephresh/rephresh/modules/emails.py", line 68, in fetch
    new_refresh_token = cls.fetch_refresh_token(
  File "/home/u213/git/squarephish/rephresh/rephresh/modules/module.py", line 90, in fetch_refresh_token
    new_refresh_token = acquire.acquire_token_by_refresh_token(
  File "/home/u213/git/squarephish/rephresh/rephresh/acquire.py", line 44, in acquire_token_by_refresh_token
    return app.acquire_token_by_refresh_token(refresh_token, scopes=scopes)
  File "/usr/lib/python3/dist-packages/msal/application.py", line 1560, in acquire_token_by_refresh_token
    response = _clean_up(self.client.obtain_token_by_refresh_token(
  File "/usr/lib/python3/dist-packages/msal/oauth2cli/oauth2.py", line 830, in obtain_token_by_refresh_token
    resp = super(Client, self).obtain_token_by_refresh_token(
  File "/usr/lib/python3/dist-packages/msal/oauth2cli/oauth2.py", line 262, in obtain_token_by_refresh_token
    return self._obtain_token("refresh_token", data=data, **kwargs)
  File "/usr/lib/python3/dist-packages/msal/oauth2cli/oidc.py", line 116, in _obtain_token
    ret = super(Client, self)._obtain_token(grant_type, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/msal/oauth2cli/oauth2.py", line 788, in _obtain_token
    (on_obtaining_tokens or self.on_obtaining_tokens)({
  File "/usr/lib/python3/dist-packages/msal/application.py", line 700, in <lambda>
    on_obtaining_tokens=lambda event: self.token_cache.add(dict(
  File "/usr/lib/python3/dist-packages/msal/token_cache.py", line 117, in add
    return self.__add(event, now=now)
  File "/usr/lib/python3/dist-packages/msal/token_cache.py", line 158, in __add
    decode_id_token(id_token, client_id=event["client_id"]) if id_token else {})
  File "/usr/lib/python3/dist-packages/msal/oauth2cli/oidc.py", line 77, in decode_id_token
    raise RuntimeError("%s Current epoch = %s.  The id_token was: %s" % (
RuntimeError: 0. The ID token is not yet valid. Make sure your computer's time and time zone are both correct. Current epoch = 1673035429.  The id_token was: {
  "aud": "d3590ed6-52b3-4102-aeff-aad2292ab01c",
  "iss": "https://login.microsoftonline.com/XXXXX-00f3-4c70-8454-2a33bdbxxxx/v2.0",
  "iat": XXXXX,
  "nbf": XXXXX,
  "exp": XXXXXXXXX,
  "aio": "ATQAy/8TAAAA/XXXXX/e1FvgSz7PdkGpxFtXz/QA/XXXXX+wtlM+XDtms",
  "name": "XXXXX XXXXX",
  "oid": "XXXXX-b2bf-44f0-958e-XXXXX",
  "preferred_username": "XXXXX.XXXXX@XXXXX.com",
  "puid": "XXXXX",
  "rh": "0.XXXXX-XXXXX.",
  "sub": "XXXXX-XXXXX",
  "tid": "XXXXX-XXXXX-XXXXX-XXXXX-XXXXX",
  "upn": "XXXXX.XXXXX@XXXXX.com",
  "uti": "XXXXX",
  "ver": "XXXXX"

**Comment by nromsdahl-scwx** [comment]
Interesting.  I have not seen this error before.  I believe the redacted IAT is 'issued at' time and according to the error maybe in the future.

One thing you could try is our tool TokenMan.  You can feed it access tokens and refresh tokens directly from the .json file.
